name: alignment
channels:
  - anaconda
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bamtools=2.5.1
  - bedtools=2.30.0
  - bioawk=1.0
  - blas=1.0
  - blast=2.5.0
  - blat=35
  - boost=1.73.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.01.10
  - curl=7.88.1
  - emboss=6.6.0
  - expat=2.4.9
  - fasta-splitter=0.2.6
  - fontconfig=2.14.1
  - freetype=2.12.1
  - giflib=5.2.1
  - gsl=2.6
  - icu=58.2
  - jemalloc=5.2.1
  - jpeg=9e
  - k8=0.2.5
  - krb5=1.19.4
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libboost=1.73.0
  - libcurl=7.88.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgd=2.3.3
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.46.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - lz4-c=1.9.4
  - mashmap=2.0
  - meryl=1.3
  - minimap2=2.17
  - ncurses=6.4
  - nomkl=3.0
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openblas=0.3.21
  - openblas-devel=0.3.21
  - openssl=1.1.1u
  - perl=5.32.1
  - perl-constant=1.33
  - perl-exporter=5.72
  - perl-file-util=4.201720
  - perl-lib=0.63
  - pip=23.0.1
  - py-boost=1.73.0
  - python=3.10.11
  - readline=8.2
  - samtools=1.6
  - seqtk=1.3
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wfmash=0.7.0
  - wheel=0.38.4
  - winnowmap=2.03
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.5
